### ISSUE TITLE
Incorrect Range Setting

### ISSUE THREAD

**Issue by dHutchings** [sparkfun/SparkFun_LIS331_Arduino_Library#1]
This is confirmed on the H3LIS331dl - YMMV on other LIS3 platforms.

The 'setFullScale' function is wrong.  It appears to work for Low and Medium ranges, but if you set the accelerometer to the HIGH range, the data is flat our inaccurate.

Line 256 of the .cpp file should read:
  data |= range<<4;
NOT
  data |= range<<5;

Without the change, if you set the accelerometer to the HIGH range, it accidentally flips the "BLE" bit - and turns the accelerometer data from Big-endian to litle-endian.

If you set the accelerometer to the MID range, it sets the FS1 / FS0 bits to an invalid state (10).

I would be happy to submit a PR if you like - although this is a quick change.

**Comment by nseidle** [comment]
Thanks for reporting! Can you point to the datasheet area where this is stated? 

A PR would be much appreciated.

**Comment by dHutchings** [comment]
Sure.  I'm referencing the datasheet here: https://cdn.sparkfun.com/assets/c/6/5/8/d/en.DM00053090.pdf

Page 27/28.  CTRL_REG4 (23h).  Note the location of FS1 and FS0.  Set full scale range twiddles those two bits.

fs_range range is a number between 0 and 4.  It should be bitshifted four to the left, not 5, to correctly fit in the FS1 and FS0 location.  Notably, line 255 uses the correct location.

The current implementation fiddles with the little / big endian settings if you attempt to set it to +/-400g range.

If you look at the LIS3DH datasheet (page 37): https://cdn.sparkfun.com/assets/b/c/1/3/a/CD00274221.pdf, you can see that this line of code would cause the same error to occur on the LIS3DH.

Also worth noting: your library doesn't make it obvious that the LIS3DH can be set into 8g mode.  That keyword is "NO_RANGE" - this setting works on the LIS3DH (8g range) but fails on the H3LIS (this is an invalid setting).  I don't address this in my PR.

PR Submitted.  Thanks!

**Comment by dHutchings** [comment]
Fixed in PR#2

**Comment by Peterpanik** [comment]
Hi 
I struck with something similar with my module (STEVAL-MKI190V1), as I am not able to change into HIGH_RANGE?
My maximum acceleration values are +-2G and it should go to +-16G?

My Arduino code seems to work fine, but this limitation in measuring range is strange.....

#include "SparkFun_LIS331.h"
#include <Wire.h>
